# Generated by Django 3.2 on 2022-12-06 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='ФИО')),
                ('price_per_meter', models.FloatField(verbose_name='Цена за метр')),
                ('number_of_porches', models.IntegerField(verbose_name='Кол-во подъездов')),
                ('number_of_floors', models.IntegerField(verbose_name='Количество этажей')),
                ('number_of_flats_per_floor', models.IntegerField(verbose_name='Кол-во квартир на этаже')),
            ],
        ),
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='ФИО владельца')),
                ('sale_date', models.DateField(blank=True, null=True, verbose_name='Дата продажи')),
                ('status', models.CharField(choices=[('Выкуп', 'Выкуп'), ('Выкуп не до конца', 'Выкуп не до конца'), ('Расторгнуто', 'Расторгнуто'), ('Не продано', 'Не продано')], max_length=30, verbose_name='Статус выкупа')),
                ('area', models.IntegerField(verbose_name='Общая площать кв.м')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.block')),
            ],
        ),
    ]
